import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ExportData {
  crawlJob: {
    id: string;
    score: number | null;
    seoScore: number | null;
    geoScore: number | null;
    aeoScore: number | null;
    pagesCrawled: number;
    errorCount: number;
    warningCount: number;
    noticeCount: number;
    completedAt: string | null;
  };
  project: {
    domain: string;
    name: string;
  };
  issues: {
    url: string;
    type: string;
    severity: string;
    dimension: string;
    message: string;
    suggestion: string | null;
  }[];
}

function formatType(type: string): string {
  return type.split('_').map(w => w.charAt(0) + w.slice(1).toLowerCase()).join(' ');
}

function getSeverityColor(severity: string): [number, number, number] {
  if (severity === 'ERROR') return [220, 38, 38];
  if (severity === 'WARNING') return [217, 119, 6];
  return [59, 130, 246];
}

function getDimColor(dim: string): [number, number, number] {
  if (dim === 'SEO') return [37, 99, 235];
  if (dim === 'GEO') return [16, 163, 74];
  return [147, 51, 234];
}

function getScoreColor(score: number | null): [number, number, number] {
  if (score === null) return [148, 163, 184];
  if (score >= 8) return [34, 197, 94];
  if (score >= 6) return [132, 204, 22];
  if (score >= 4) return [234, 179, 8];
  return [239, 68, 68];
}

export function generateAuditPdf(data: ExportData) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  // ============ COVER PAGE ============
  // Navy background
  doc.setFillColor(27, 42, 74);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F');

  // Domain title
  y = 60;
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text(data.project.domain, pageWidth / 2, y, { align: 'center' });

  // Subtitle
  y += 14;
  doc.setFontSize(16);
  doc.setTextColor(147, 197, 253);
  doc.text('SEO / GEO / AEO Audit Report', pageWidth / 2, y, { align: 'center' });

  // Date
  y += 10;
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  const dateStr = data.crawlJob.completedAt
    ? new Date(data.crawlJob.completedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : 'N/A';
  doc.text(`Audit Date: ${dateStr}`, pageWidth / 2, y, { align: 'center' });

  // Score boxes
  y += 25;
  const boxWidth = 45;
  const boxGap = 10;
  const totalBoxes = 3 * boxWidth + 2 * boxGap;
  const boxStartX = (pageWidth - totalBoxes) / 2;

  const scores = [
    { label: 'SEO', score: data.crawlJob.seoScore, max: 10 },
    { label: 'GEO', score: data.crawlJob.geoScore, max: 10 },
    { label: 'AEO', score: data.crawlJob.aeoScore, max: 10 },
  ];

  scores.forEach((s, i) => {
    const x = boxStartX + i * (boxWidth + boxGap);
    const [r, g, b] = getScoreColor(s.score);
    doc.setFillColor(r, g, b);
    doc.roundedRect(x, y, boxWidth, 35, 3, 3, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(s.label, x + boxWidth / 2, y + 10, { align: 'center' });

    doc.setFontSize(24);
    doc.text(`${s.score ?? '-'}`, x + boxWidth / 2, y + 24, { align: 'center' });

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`/ ${s.max}`, x + boxWidth / 2, y + 31, { align: 'center' });
  });

  // Health score circle
  y += 50;
  doc.setFillColor(255, 255, 255);
  doc.circle(pageWidth / 2, y + 15, 20, 'F');
  const healthScore = data.crawlJob.score ?? 0;
  const [hr, hg, hb] = healthScore >= 70 ? [34, 197, 94] : healthScore >= 40 ? [234, 179, 8] : [239, 68, 68];
  doc.setTextColor(hr, hg, hb);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(`${healthScore}`, pageWidth / 2, y + 18, { align: 'center' });
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('HEALTH', pageWidth / 2, y + 25, { align: 'center' });

  // Stats
  y += 45;
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `${data.crawlJob.pagesCrawled} Pages Crawled  |  ${data.crawlJob.errorCount} Errors  |  ${data.crawlJob.warningCount} Warnings  |  ${data.crawlJob.noticeCount} Notices`,
    pageWidth / 2, y, { align: 'center' }
  );

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by NR SEO Platform', pageWidth / 2, 275, { align: 'center' });

  // ============ PAGE 2: SUMMARY ============
  doc.addPage();
  doc.setTextColor(30, 41, 59);

  y = 20;
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Audit Summary', margin, y);

  y += 12;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  // Summary table
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Metric', 'Value']],
    body: [
      ['Domain', data.project.domain],
      ['Project', data.project.name],
      ['Pages Crawled', String(data.crawlJob.pagesCrawled)],
      ['Health Score', `${data.crawlJob.score ?? '-'} / 100`],
      ['SEO Score', `${data.crawlJob.seoScore ?? '-'} / 10`],
      ['GEO Score', `${data.crawlJob.geoScore ?? '-'} / 10`],
      ['AEO Score', `${data.crawlJob.aeoScore ?? '-'} / 10`],
      ['Total Errors', String(data.crawlJob.errorCount)],
      ['Total Warnings', String(data.crawlJob.warningCount)],
      ['Total Notices', String(data.crawlJob.noticeCount)],
      ['Audit Date', dateStr],
    ],
    theme: 'grid',
    headStyles: { fillColor: [27, 42, 74], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 249, 250] },
    styles: { fontSize: 10, cellPadding: 4 },
  });

  // ============ ISSUES BY DIMENSION ============
  const dimensions = ['SEO', 'GEO', 'AEO'];

  for (const dim of dimensions) {
    const dimIssues = data.issues.filter(i => i.dimension === dim);
    if (dimIssues.length === 0) continue;

    doc.addPage();
    y = 20;

    const [dr, dg, db] = getDimColor(dim);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(dr, dg, db);
    doc.text(`${dim} Issues (${dimIssues.length})`, margin, y);

    y += 4;
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    const dimLabel = dim === 'SEO' ? 'Search Engine Optimization' : dim === 'GEO' ? 'Generative Engine Optimization (AI Search)' : 'Answer Engine Optimization';
    doc.text(dimLabel, margin, y + 6);

    y += 12;

    // Issues table
    const tableData = dimIssues.map(issue => [
      issue.url.replace(/^https?:\/\//, '').slice(0, 45),
      formatType(issue.type),
      issue.severity,
      issue.message,
      issue.suggestion || '',
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Page URL', 'Issue', 'Severity', 'Details', 'How to Fix']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [27, 42, 74], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
      alternateRowStyles: { fillColor: [248, 249, 250] },
      styles: { fontSize: 7, cellPadding: 3, overflow: 'linebreak' },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 25 },
        2: { cellWidth: 15 },
        3: { cellWidth: 40 },
        4: { cellWidth: contentWidth - 35 - 25 - 15 - 40 },
      },
      didParseCell: (hookData: any) => {
        // Color-code severity column
        if (hookData.column.index === 2 && hookData.section === 'body') {
          const [r, g, b] = getSeverityColor(hookData.cell.raw as string);
          hookData.cell.styles.textColor = [255, 255, 255];
          hookData.cell.styles.fillColor = [r, g, b];
          hookData.cell.styles.fontStyle = 'bold';
          hookData.cell.styles.halign = 'center';
        }
      },
    });
  }

  // ============ ALL ISSUES (FULL LIST) ============
  doc.addPage();
  y = 20;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`All Issues (${data.issues.length})`, margin, y);

  y += 10;

  const allTableData = data.issues.map(issue => [
    issue.url.replace(/^https?:\/\//, '').slice(0, 35),
    issue.dimension,
    formatType(issue.type),
    issue.severity,
    issue.message,
    issue.suggestion || '',
  ]);

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Page URL', 'Dim', 'Issue', 'Severity', 'Details', 'How to Fix']],
    body: allTableData,
    theme: 'grid',
    headStyles: { fillColor: [27, 42, 74], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7 },
    alternateRowStyles: { fillColor: [248, 249, 250] },
    styles: { fontSize: 6.5, cellPadding: 2.5, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 10 },
      2: { cellWidth: 22 },
      3: { cellWidth: 13 },
      4: { cellWidth: 38 },
      5: { cellWidth: contentWidth - 30 - 10 - 22 - 13 - 38 },
    },
    didParseCell: (hookData: any) => {
      if (hookData.column.index === 3 && hookData.section === 'body') {
        const [r, g, b] = getSeverityColor(hookData.cell.raw as string);
        hookData.cell.styles.textColor = [255, 255, 255];
        hookData.cell.styles.fillColor = [r, g, b];
        hookData.cell.styles.fontStyle = 'bold';
        hookData.cell.styles.halign = 'center';
      }
      // Dimension column color
      if (hookData.column.index === 1 && hookData.section === 'body') {
        const [r, g, b] = getDimColor(hookData.cell.raw as string);
        hookData.cell.styles.textColor = [r, g, b];
        hookData.cell.styles.fontStyle = 'bold';
        hookData.cell.styles.halign = 'center';
      }
    },
  });

  // ============ FOOTER ON EACH PAGE ============
  const totalPages = doc.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.project.domain} — SEO/GEO/AEO Audit Report`, margin, 290);
    doc.text(`Page ${i - 1} of ${totalPages - 1}`, pageWidth - margin, 290, { align: 'right' });
  }

  // Save
  const filename = `audit-${data.project.domain.replace(/\./g, '-')}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
