import Head from 'next/head';
import Link from 'next/link';
import { AuthGuard } from '@/components/auth/AuthGuard';
import { Sidebar, sidebarStyles } from '@/components/layout/Sidebar';
import styles from './index.module.css';

const TOOLS = [
  {
    icon: '🔍',
    title: 'Keyword Research',
    desc: 'Discover what people search for on Google. Get volume, difficulty, CPC, intent, and related keyword suggestions with advanced filters.',
    href: '/dashboard/keywords',
  },
  {
    icon: '🌐',
    title: 'Domain Overview',
    desc: 'Get a complete SEO snapshot of any domain — authority score, traffic, backlinks, top keywords, competitors, and country distribution.',
    href: '/dashboard/domain-overview',
  },
  {
    icon: '📈',
    title: 'Organic Rankings',
    desc: 'See what keywords any domain ranks for in Google. Analyze positions, changes, competitors, and top pages across 4 tabs.',
    href: '/dashboard/organic-rankings',
  },
  {
    icon: '📄',
    title: 'Top Pages',
    desc: 'Find the best-performing pages on any domain ranked by organic traffic, with keyword counts, backlinks, and trend sparklines.',
    href: '/dashboard/top-pages',
  },
  {
    icon: '⚖️',
    title: 'Compare Domains',
    desc: 'Put 2-5 websites side-by-side. Compare authority, traffic, keywords, backlinks, intent, and keyword overlap with visual charts.',
    href: '/dashboard/compare-domains',
  },
  {
    icon: '🔀',
    title: 'Keyword Gap',
    desc: 'Find keywords your competitors rank for that you don\'t. Classify gaps as Missing, Weak, Strong, Untapped, or Unique.',
    href: '/dashboard/keyword-gap',
  },
  {
    icon: '🔗',
    title: 'Backlink Gap',
    desc: 'Discover which websites link to your competitors but not you. Identify top link-building targets sorted by authority.',
    href: '/dashboard/backlink-gap',
  },
  {
    icon: '🛠',
    title: 'Site Audit',
    desc: 'Crawl your website to find SEO, GEO, and AEO issues. Get a health score, severity breakdown, and actionable fix suggestions.',
    href: '/dashboard',
  },
  {
    icon: '📊',
    title: 'Position Tracking',
    desc: 'Monitor your keyword rankings daily. Track visibility score, estimated traffic, position changes, and ranking distribution over time.',
    href: '/dashboard',
  },
];

const FEATURES = [
  { icon: '🤖', name: 'AI-Powered Data', desc: 'All competitive intelligence is generated by OpenAI, providing instant estimates for any domain without expensive third-party API subscriptions.' },
  { icon: '⚡', name: '7-Day Smart Cache', desc: 'Results are cached for 7 days per domain. First lookup takes a moment, but subsequent queries for the same domain are instant.' },
  { icon: '🌙', name: 'Dark Mode', desc: 'Full dark mode support across every page. Toggle with one click from the sidebar.' },
  { icon: '📱', name: 'Responsive Design', desc: 'Every tool works on desktop, tablet, and mobile with adaptive layouts.' },
  { icon: '📊', name: 'Interactive Charts', desc: 'Line charts, bar charts, pie charts, scatter plots, and sparklines powered by Recharts for rich data visualization.' },
  { icon: '🔒', name: 'Secure & Private', desc: 'JWT authentication, project-level authorization, encrypted connections, and role-based access control.' },
];

function AboutContent() {
  return (
    <div className={styles.layout}>
      <Head>
        <title>About NR SEO Platform</title>
      </Head>
      <Sidebar />
      <div className={sidebarStyles.contentWithSidebar}>
        <main className={styles.main}>
          <h1 className={styles.pageTitle}>NR SEO Platform</h1>
          <p className={styles.pageSubtitle}>
            A comprehensive SEO toolkit inspired by Semrush. Research keywords, analyze competitors,
            audit your site, track rankings, and discover growth opportunities — all powered by AI.
          </p>

          {/* Tools Grid */}
          <div className={styles.toolsGrid}>
            {TOOLS.map((tool) => (
              <Link key={tool.title} href={tool.href} className={styles.toolCard}>
                <div className={styles.toolCardIcon}>{tool.icon}</div>
                <div className={styles.toolCardTitle}>{tool.title}</div>
                <div className={styles.toolCardDesc}>{tool.desc}</div>
              </Link>
            ))}
          </div>

          {/* How It Works */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>How It Works</h2>
            <p className={styles.sectionText}>
              NR SEO Platform uses OpenAI to generate realistic SEO estimates for any domain.
              Simply enter a domain or keyword, and get instant data — no complex setup, no
              third-party API keys required (beyond OpenAI).
            </p>
            <p className={styles.sectionText}>
              Results are cached for 7 days, so the first lookup may take a few seconds while AI
              generates the data, but subsequent lookups for the same domain are instant.
            </p>
            <p className={styles.sectionText}>
              For your own projects, use Site Audit to crawl your website and find real SEO issues,
              and Position Tracking to monitor your actual keyword rankings over time.
            </p>
          </div>

          {/* Platform Features */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Platform Features</h2>
            <ul className={styles.featureList}>
              {FEATURES.map((f) => (
                <li key={f.name} className={styles.featureItem}>
                  <span className={styles.featureIcon}>{f.icon}</span>
                  <div className={styles.featureContent}>
                    <div className={styles.featureName}>{f.name}</div>
                    <div className={styles.featureDesc}>{f.desc}</div>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          {/* Getting Started */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Getting Started</h2>
            <p className={styles.sectionText}>
              <strong>1. Explore any domain</strong> — Start with Domain Overview or Organic Rankings.
              Enter a competitor's domain to see their SEO profile instantly.
            </p>
            <p className={styles.sectionText}>
              <strong>2. Research keywords</strong> — Use Keyword Research to find high-volume,
              low-difficulty keywords in your niche. Save the best ones to your project.
            </p>
            <p className={styles.sectionText}>
              <strong>3. Create a project</strong> — Go to Dashboard and create a project for your
              domain. Add competitors, save keywords, and start tracking rankings.
            </p>
            <p className={styles.sectionText}>
              <strong>4. Audit your site</strong> — Run a Site Audit to find technical SEO issues.
              Fix errors first, then warnings, to improve your health score.
            </p>
            <p className={styles.sectionText}>
              <strong>5. Find gaps</strong> — Use Keyword Gap and Backlink Gap to discover what
              your competitors have that you don't. These are your growth opportunities.
            </p>
            <p className={styles.sectionText}>
              <strong>6. Track progress</strong> — Set up Position Tracking with daily checks to
              monitor how your rankings improve over time.
            </p>
          </div>

          {/* Plans */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Plans</h2>
            <p className={styles.sectionText}>
              Three tiers to match your needs. All plans include access to every tool.
            </p>
            <div className={styles.plansGrid}>
              <div className={styles.planCard}>
                <div className={styles.planName}>Free</div>
                <div className={styles.planFeature}>1 project</div>
                <div className={styles.planFeature}>10 tracked keywords</div>
                <div className={styles.planFeature}>3 lookups/day per tool</div>
                <div className={styles.planFeature}>10 keyword searches/day</div>
                <div className={styles.planFeature}>3 months data retention</div>
              </div>
              <div className={styles.planCard}>
                <div className={styles.planName}>Pro</div>
                <div className={styles.planFeature}>5 projects</div>
                <div className={styles.planFeature}>100 tracked keywords</div>
                <div className={styles.planFeature}>50 lookups/day per tool</div>
                <div className={styles.planFeature}>500 keyword searches/day</div>
                <div className={styles.planFeature}>12 months data retention</div>
              </div>
              <div className={styles.planCard}>
                <div className={styles.planName}>Agency</div>
                <div className={styles.planFeature}>25 projects</div>
                <div className={styles.planFeature}>1,000 tracked keywords</div>
                <div className={styles.planFeature}>Unlimited lookups</div>
                <div className={styles.planFeature}>Unlimited searches</div>
                <div className={styles.planFeature}>24 months data retention</div>
              </div>
            </div>
          </div>

          {/* Tip */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Need Help?</h2>
            <p className={styles.sectionText}>
              Every tool has a <strong>?</strong> button next to the page title. Click it to open a
              guide explaining what the tool does, how to use it, and pro tips for getting the most
              out of it.
            </p>
          </div>
        </main>
      </div>
    </div>
  );
}

export default function AboutPage() {
  return (
    <AuthGuard>
      <AboutContent />
    </AuthGuard>
  );
}
