-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "IssueType" ADD VALUE 'ROBOTS_TXT_MISSING';
ALTER TYPE "IssueType" ADD VALUE 'ROBOTS_TXT_SYNTAX_ERROR';
ALTER TYPE "IssueType" ADD VALUE 'ROBOTS_TXT_BLOCKS_IMPORTANT';
ALTER TYPE "IssueType" ADD VALUE 'ROBOTS_TXT_BLOCKS_ASSETS';
ALTER TYPE "IssueType" ADD VALUE 'ROBOTS_TXT_NO_SITEMAP_REF';
ALTER TYPE "IssueType" ADD VALUE 'SITEMAP_MISSING';
ALTER TYPE "IssueType" ADD VALUE 'SITEMAP_INVALID_XML';
ALTER TYPE "IssueType" ADD VALUE 'SITEMAP_CANONICAL_MISMATCH';
ALTER TYPE "IssueType" ADD VALUE 'HTTP_NOT_REDIRECTING_TO_HTTPS';
ALTER TYPE "IssueType" ADD VALUE 'WWW_REDIRECT_INCONSISTENT';
ALTER TYPE "IssueType" ADD VALUE 'REDIRECT_LOOP';
ALTER TYPE "IssueType" ADD VALUE 'TRAILING_SLASH_INCONSISTENT';
ALTER TYPE "IssueType" ADD VALUE 'FAVICON_MISSING';
ALTER TYPE "IssueType" ADD VALUE 'CUSTOM_404_MISSING';
ALTER TYPE "IssueType" ADD VALUE 'PAGE_TOO_DEEP';
ALTER TYPE "IssueType" ADD VALUE 'URL_USES_UNDERSCORES';
ALTER TYPE "IssueType" ADD VALUE 'URL_HAS_EXCESS_PARAMS';
ALTER TYPE "IssueType" ADD VALUE 'HEADING_HIERARCHY_BROKEN';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_BREADCRUMBS';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_BREADCRUMB_SCHEMA';
ALTER TYPE "IssueType" ADD VALUE 'PAGINATION_BROKEN';
ALTER TYPE "IssueType" ADD VALUE 'CANONICAL_CONFLICT';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_HSTS_HEADER';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_CSP_HEADER';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_X_FRAME_OPTIONS';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_REFERRER_POLICY';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_X_CONTENT_TYPE_OPTIONS';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_PERMISSIONS_POLICY';
ALTER TYPE "IssueType" ADD VALUE 'SSL_CERT_EXPIRING_SOON';
ALTER TYPE "IssueType" ADD VALUE 'SSL_CERT_INVALID';
ALTER TYPE "IssueType" ADD VALUE 'EXCESSIVE_DOM_NODES';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_LAZY_LOADING';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_IMG_DIMENSIONS';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_NEXT_GEN_IMAGE_FORMAT';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_FONT_DISPLAY_SWAP';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_PRECONNECT_HINTS';
ALTER TYPE "IssueType" ADD VALUE 'IMAGE_FILENAME_NOT_DESCRIPTIVE';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_CACHE_HEADERS';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_COMPRESSION';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_PRODUCT_SCHEMA';
ALTER TYPE "IssueType" ADD VALUE 'MISSING_ARTICLE_SCHEMA';
ALTER TYPE "IssueType" ADD VALUE 'OG_IMAGE_TOO_SMALL';
ALTER TYPE "IssueType" ADD VALUE 'HREFLANG_MISSING';
ALTER TYPE "IssueType" ADD VALUE 'HREFLANG_INVALID_CODE';
ALTER TYPE "IssueType" ADD VALUE 'HREFLANG_NOT_RECIPROCAL';
ALTER TYPE "IssueType" ADD VALUE 'HREFLANG_MISSING_SELF';
ALTER TYPE "IssueType" ADD VALUE 'HREFLANG_MISSING_X_DEFAULT';
ALTER TYPE "IssueType" ADD VALUE 'GA_TRACKING_MISSING';
ALTER TYPE "IssueType" ADD VALUE 'GTM_TAG_MISSING';
ALTER TYPE "IssueType" ADD VALUE 'AMP_INVALID';
ALTER TYPE "IssueType" ADD VALUE 'POOR_LCP';
ALTER TYPE "IssueType" ADD VALUE 'POOR_CLS';
ALTER TYPE "IssueType" ADD VALUE 'POOR_INP';
ALTER TYPE "IssueType" ADD VALUE 'RENDER_BLOCKING_CSS';
ALTER TYPE "IssueType" ADD VALUE 'RENDER_BLOCKING_JS';
ALTER TYPE "IssueType" ADD VALUE 'EXCESSIVE_PAGE_WEIGHT';
ALTER TYPE "IssueType" ADD VALUE 'GSC_NOT_VERIFIED';
ALTER TYPE "IssueType" ADD VALUE 'GSC_HAS_MANUAL_ACTION';
ALTER TYPE "IssueType" ADD VALUE 'GSC_SECURITY_ISSUE';
ALTER TYPE "IssueType" ADD VALUE 'BING_NOT_VERIFIED';
ALTER TYPE "IssueType" ADD VALUE 'SCHEMA_VALIDATION_FAILED';
